bboard/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('api/', include('modules.api.urls')),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),

]

urlpatterns += i18n_patterns(
    path('', include('modules.main.urls', namespace='main')),
    path('', include('modules.cms.urls', namespace='cms')),
    path('', include('modules.shops.urls', namespace='shops')),
    path('', include('modules.cart.urls', namespace='cart')),
    path('', include('modules.users.urls', namespace='users')),
    path('', include('modules.orders.urls', namespace='orders')),
    path('', include('modules.delivery.urls', namespace='delivery')),
    path('', include('modules.favorite.urls', namespace='favorite')),
    # path('', include('modules.chat.urls', namespace='chat')),
    path('', include('social_django.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        ] + urlpatterns

modules/cms/urls.py
from django.urls import path

from modules.cms import views
from modules.cms.views import AboutView, HelpView, LicenseView, FeedbackView

app_name = 'cms'

urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
    path('help/', HelpView.as_view(), name='help'),
    path('license/', LicenseView.as_view(), name='license'),
    path('feedback/', FeedbackView.as_view(), name='feedback'),
]

modules/main/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from modules.main.views import (
    ProductDetail,
    ItemCreateView,
    ItemEditView,
    ItemDeleteView,
    CategoryList,
    SearchResultView,
    IndexView,
    ItemList,

)

app_name = 'main'

urlpatterns = [
    path('advert/', ItemList.as_view(), name='advert-list'),
    path('product/', ItemList.as_view(), name='product-list'),

    path('product/<int:pk>', ProductDetail.as_view(), name='product-detail'),
    path('product/create', ItemCreateView.as_view(), name='product-create'),
    path('product/edit/<int:pk>', never_cache(ItemEditView.as_view()), name='product-edit'),
    path('product/delete/<int:pk>', ItemDeleteView.as_view(), name='product-delete'),

    # Работа с категориями
    path('category/<int:pk>', CategoryList.as_view(), name='category'),

    path('search/', SearchResultView.as_view(), name='search-result'),

    path('city/<int:city_pk>/', IndexView.as_view(), name='index'),

    path('', IndexView.as_view(), name='index'),
]

modules/orders/urls.py
from django.urls import path

from modules.orders.views import OrderCreateView

app_name = 'orders'

urlpatterns = [
    path('order/create/', OrderCreateView.as_view(), name='order-create'),
]

modules/shops/urls.py
from django.urls import path

from modules.shops.views import (
    ShopsList,
    ShopPageView,
    ShopCreateView,
    ShopInfoView,
    ShopProductCreate,
    ShopProductEdit,
    ShopProductDeleteView,
    ShopInfoEdit,
    ShopProductList,
    ShopOrdersListView,
    ShopCreateSuccsessView,
)

app_name = 'shops'

urlpatterns = [
    # список всех магазинов
    path('shops/', ShopsList.as_view(), name='shops-list'),

    # заявка на создание магазина
    path('shop/shop-create/', ShopCreateView.as_view(), name='shop-create'),
    path('shop/shop-create/success', ShopCreateSuccsessView.as_view(), name='shop-create-success'),

    # страница магазина
    path('shop/<int:pk>', ShopPageView.as_view(), name='shop-page'),

    # управление магазином
    path('account/<int:pk>/shops/', ShopInfoView.as_view(), name='shop-info'),
    path('shop/info/<int:pk>/edit', ShopInfoEdit.as_view(), name='shop-info-edit'),

    # список товаров магазина
    path('shop/<int:pk>/product-list', ShopProductList.as_view(), name='crud-product'),

    # создание товара в определенном магазине
    path('shop/<int:shop_pk>/create-product', ShopProductCreate.as_view(), name='create-product'),

    # редактирование товара в определенном магазине
    # path('shop/<int:shop_pk>/product/<int:pk>/edit/', ShopProductEdit.as_view(), name='shop-product-edit'),
    path('shop/<int:shop_pk>/product/<int:pk>/edit/', ShopProductEdit.as_view(), name='product-edit'),
    path('shop/product/<int:pk>/delete/', ShopProductDeleteView.as_view(), name='product-delete'),

    # список заказов
    path('shop/<int:shop_pk>/orders', ShopOrdersListView.as_view(), name='order-list'),
]

modules/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordResetCompleteView, PasswordChangeDoneView, \
    PasswordResetConfirmView, PasswordResetView
from django.urls import path, reverse_lazy

from modules.users.views import (
    ValidateView,
    AccountLoginView,
    RegistrationView,
    AccountDetailView,
    AccountSettingsView,
    HistoryOrderView,
    HistoryOrderDetailView
)

app_name = 'users'

urlpatterns = [
    # вход/выход/регистрация
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),

    path('registration', RegistrationView.as_view(), name='registration'),
    path('registration/validate-email/', ValidateView.as_view()),

    path('account/settings/<int:pk>', AccountSettingsView.as_view(), name='settings-profile'),

    # my bb
    path('account/<int:pk>', AccountDetailView.as_view(), name='account-detail'),

    # history orders
    path('account/<int:pk>/orders/', HistoryOrderView.as_view(), name='history-orders'),
    path('account/<int:pk>/orders/<int:order_pk>', HistoryOrderDetailView.as_view(), name='history-detail-orders'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # reset password
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='registration/password-change-done.html'),
         name='password_change_done'),

    path('password_change/',
         PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done'),
                                    template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/',
         PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_complete')),
         name='password-reset'),

    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

modules/users/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.contrib.auth.forms import UserCreationForm

from modules.users.models import Account


class RegisterForm(UserCreationForm):
    class Meta:
        model = Account
        fields = ('username',
                  'first_name',
                  'last_name',
                  'phone',
                  'city',
                  'email',
                  'password1',
                  'password2')


class EditAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'phone',
            'city',
            'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Сохранить'))

modules/users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views import View
from django.views.generic import DetailView, UpdateView, TemplateView

from modules.area.models import City
from modules.main.models import Item
from modules.main.views import CartItemCountMixin
from modules.orders.models import Order
from modules.users.forms import RegisterForm, EditAccountForm
from modules.users.models import Account


class ValidateView(View):

    def get(self, request):
        email = request.GET.get('email')
        username = request.GET.get('username')

        # Поле юзера не пустое, доп проверка
        if username != "":
            check_username = Account.objects.filter(username=username).exists()
            print('check_username', check_username)

        # Поле емейла не пустое
        if email != '':
            try:
                validate_email(email)

                if Account.objects.filter(email__iexact=email).exists():
                    return JsonResponse({
                        "success": False,
                        'error_message': 'A user with this email already exists.'
                    })

            except ValidationError as e:
                return JsonResponse({
                    "success": False,
                    'error_message': 'Email not valid',
                })

        else:
            return JsonResponse({
                "success": False,
                'error_message': 'Email field is empty',
            })

        # если емейл валидный
        return JsonResponse({
            "success": True
        })


# TODO: заблочить показ логин страницы если юзер авторизирован
class RegistrationView(View):

    def get_success_url(self):
        return reverse('main:login')

    def post(self, request, *args, **kwargs):
        registration_form = RegisterForm(request.POST or None)

        # TODO: добавить обработку ошибок в форме, валидация
        # Account.objects.all().order_by('-date_joined')

        if registration_form.is_valid():

            registration_form.save()

            # TODO: нужен ли автологин после регистрации

            # TODO: отправка емейла для подтверждения активации -
            # нужно поле статуса активации в модели Account
            # отправка почты, кеш под хеши ссылок
            # TODO: отправка емейла для подтверждения
            # TODO: не работает сброс пароля

            return JsonResponse({"ok": "You registered!"})

        else:
            return JsonResponse({'success': False,
                                 'errors': [(k, v[0]) for k, v in registration_form.errors.items()]
                                 })


class AccountLoginView(TemplateView):
    template_name = 'login.html'
    form_class = AuthenticationForm

    def post(self, request, *args, **kwargs):

        login_form = AuthenticationForm(data={
            "username": request.POST["username"],
            "password": request.POST["password"]
        })

        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')

            user = authenticate(username=username, password=password, request=self.request)

            if user is not None:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')

                return redirect('/')

            else:

                return JsonResponse({'success': False,
                                     'errors': [
                                         {
                                             'some': 'wrong'
                                         },
                                     ]})
        else:
            if request.POST["username"] != "":
                return JsonResponse({'success': False,
                                     'errors': [
                                         {
                                             'username': 'username empty'
                                         },
                                     ]})

            if request.POST["password"] != "":
                return JsonResponse({'success': False,
                                     'errors': [
                                         {
                                             'password': 'password empty'
                                         },
                                     ]})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['city_list'] = City.objects.all()
        return context


class HistoryOrderView(DetailView, LoginRequiredMixin, CartItemCountMixin):
    model = Account
    template_name = 'history-orders.html'
    # TODO add paginate to order table


class HistoryOrderDetailView(DetailView, LoginRequiredMixin, CartItemCountMixin):
    model = Order
    template_name = 'history-detail-orders.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['account'] = Account.objects.get(id=self.request.user.id)

        return context


class AccountDetailView(DetailView, CartItemCountMixin):
    model = Account
    template_name = 'account-detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['account'] = Account.objects.get(id=self.kwargs.get('pk'))

        return context


class AccountSettingsView(LoginRequiredMixin, UpdateView, CartItemCountMixin):
    model = Account
    template_name = 'account-settings.html'
    context_object_name = 'account'
    form_class = EditAccountForm
    slug_url_kwarg = 'name'

    def get_success_url(self):
        return reverse('users:account-detail', args=[self.kwargs.get("pk")])

modules/users/templates/account-detail.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% load static %}
{% load i18n %}

{% block title %}
    {% if user.is_anonymous %}
        {% trans 'Объявления пользователя' %}: {{ account.username }}
    {% else %}
        {% trans 'Мои объявления' %}
    {% endif %}
{% endblock %}


{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb col-md-12 mt-5 mb-5">
                <li class="breadcrumb-item">
                    <a class="breadcrumb-link" href="/">{% trans 'Главная' %}</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">{% trans 'Профиль' %}</li>
            </ol>
        </nav>
        <div class="row pb-5 col-md-12">
            <div class="col-md-3">
                {% include 'account-sidebar-block.html' %}
            </div>
            <div class="col-md-9">
                {{ account.get_product_count_active }}
                <div class="account-products mt-3">
                    <h1 class="h1 title mt-3 pb-3">
                        {% if user.id == account.id %}
                            {% trans 'Мои объявления' %}
                        {% else %}
                            {% trans 'Объявления пользователя' %}: {{ account.username }}
                        {% endif %}
                    </h1>

                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                               aria-controls="home" aria-selected="true"> {% trans 'Активные' %} <span
                                    class="badge badge-secondary">{{ account.get_items_count_active | default_if_none:0 }}</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab"
                               aria-controls="profile" aria-selected="false">{% trans 'Завершенные' %} <span
                                    class="badge badge-secondary">{{ account.get_items_count_no_active | default_if_none:0 }}</span></a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            {% if account.get_items_count_active %}
                                <div class="row mt-3">
                                    {% for product in account.get_items_active %}
                                        <div class="card card-product-grid">
                                            <a class="img-wrap" href="{{ product.get_absolute_url }}">
                                                {% if product.get_main_image %}
                                                    <img class="card-img-top" width="216" height="140"
                                                         src="{% thumbnail product.get_main_image.images 216x140 crop=scale %}"
                                                         alt="{{ product.name }}">

                                                {% else %}
                                                    {% if product.get_main_image %}
                                                        <img height="131" width="131"
                                                             src="{% thumbnail product.get_main_image.image 131x131 crop=scale %}"
                                                             alt="{{ product.name }}">
                                                    {% else %}
                                                        <img height="131" width="131"
                                                             src="{% static 'img/slider/no-image.png' %}"
                                                             alt="{{ product.name }}">
                                                    {% endif %}
                                                {% endif %}

                                                <a href="{{ product.get_absolute_url }}">
                                                    <div class="product-card-like">
                                                        <i class="far fa-heart"></i>
                                                    </div>
                                                </a>
                                                <div class="card-body">
                                                    <h5 class="product-card-title" data-placement="right"
                                                        title="{{ product.name }}">
                                                        <a class="product-link"
                                                           href="{{ product.get_absolute_url }}">{{ product.name|truncatechars:19 }}</a>
                                                    </h5>
                                                    <div class="product-card-price">
                                                        {{ product.price| floatformat }}{{ product.currency }}</div>
                                                    {% if product.city_bb %}
                                                        {{ product.city_bb }}
                                                    {% endif %}
                                                    <div class="mt-2">
                                                        <hr>
                                                        {% if user.id == account.id %}
                                                            <a class="btn btn-info"
                                                               href="{% url 'main:product-edit' pk=product.id %}">{% trans 'Изменить' %}</a>
                                                            <a class="btn btn-warning"
                                                               href="{% url 'main:product-delete' pk=product.id %}">{% trans 'Удалить' %}</a>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% else %}
                                <div class="row">
                                    <p> {% trans 'Пока нет объявлений' %}</p>
                                    <a class="btn-create-announcement mx-3 mt-1 mb-1"
                                       href="{% url 'main:product-create' %}">{% trans 'Создать объявление' %}</a>
                                </div>
                            {% endif %}
                        </div>
                        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            {% if account.get_items_count_no_active %}
                                <div class="row mt-3">
                                    {% for product in account.get_items_no_active %}
                                        <div class="card card-product-grid">
                                            <a class="img-wrap" href="{{ product.get_absolute_url }}">
                                                {% if product.get_main_image %}
                                                    <img class="card-img-top" width="216" height="140"
                                                         src="{% thumbnail product.get_main_image.images 216x140 crop=scale %}"
                                                         alt="{{ product.name }}">

                                                {% else %}
                                                    {% if product.get_main_image %}
                                                        <img height="131" width="131"
                                                             src="{% thumbnail product.get_main_image.image 131x131 crop=scale %}"
                                                             alt="{{ product.name }}">
                                                    {% else %}
                                                        <img height="131" width="131"
                                                             src="{% static 'img/slider/no-image.png' %}"
                                                             alt="{{ product.name }}">
                                                    {% endif %}
                                                {% endif %}

                                                <a href="{{ product.get_absolute_url }}">
                                                    <div class="product-card-like">
                                                        <i class="far fa-heart"></i>
                                                    </div>
                                                </a>
                                                <div class="card-body">
                                                    <h5 class="product-card-title" data-placement="right"
                                                        title="{{ product.name }}">
                                                        <a class="product-link"
                                                           href="{{ product.get_absolute_url }}">{{ product.name|truncatechars:19 }}</a>
                                                    </h5>
                                                    <div class="product-card-price">
                                                        {{ product.price| floatformat }}{{ product.currency }}</div>
                                                    {% if product.city_bb %}
                                                        {{ product.city_bb }}
                                                    {% endif %}

                                                    <div class="mt-2">
                                                        <hr>
                                                        {% if user.id == account.id %}
                                                            <a class="btn btn-info"
                                                               href="{% url 'main:product-edit' pk=product.id %}">{% trans 'Изменить' %}</a>
                                                            <a class="btn btn-warning"
                                                               href="{% url 'main:product-delete' pk=product.id %}">{% trans 'Удалить' %}</a>
                                                        {% endif %}
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>

{% endblock %}

modules/users/templates/account-sidebar-block.html
{% load static %}
{% load thumbnail %}
{% load i18n %}

<div class="account-sidebar">
    <div class="row">
        <div class="account-photo">
            {% if account.avatar %}
                <img src="{% thumbnail account.avatar 48x48 crop=scale %}" alt="">
            {% else %}
                <img class="img-thumbnail" src="{% static 'img/blank-profile-picture.png' %}" alt="">
            {% endif %}
        </div>
        <div class="account-info">
            <div class="account-name">{{ account.username }}</div>
            {# TODO: rating account #}
            {# <div class="my-advert__info-star">#}
            {# <i class="fas fa-star"></i>4.9/5#}
            {# </div> #}
        </div>
    </div>
    <div class="account-location">
        <i class="fas fa-location-arrow"></i>
        {% if account.city %}
            <a href="{% url "main:index" city_pk=account.city.id %}">
                {{ account.city.name }}
            </a>
        {% else %}
            <span class="badge-danger">{% trans 'Город: ' %}{{ account.city }}</span>
        {% endif %}
        <p>{% trans 'На сайте с' %} {{ account.date_joined | date:"d M Y" }}</p>
    </div>
    <div class="account-menu">
        {% if user.id == account.id %}
            <a href="{% url 'users:account-detail' pk=account.id %}"
               class="account-menu--item {% if request.resolver_match.url_name == "account-detail" %}
                                account-menu--item--active {% endif %}">
                <i class="far fa-list-alt fa-2x pt-1 pb-1 mr-3"></i>
                {% trans 'Мои объявления' %}
            </a>

            <a href="{% url 'users:history-orders' pk=account.id %}"
               class="account-menu--item {% if request.resolver_match.url_name == 'history-orders' %}
                                account-menu--item--active {% endif %}">
                <i class="fas fa-archive fa-2x pt-1 pb-1 mr-3"></i>
                {% trans 'Мои заказы' %}
            </a>

            <a href="{% url 'users:settings-profile' pk=user.id %}"
               class="account-menu--item {% if request.resolver_match.url_name == 'settings-profile' %}
                                account-menu--item--active {% endif %}">

                <i class="fa fa-cogs fa-2x pt-1 pb-1 mr-3"></i>
                {% trans 'Настройки' %}
            </a>

            {% if user.shop_owner %}
                <a href="{% url 'shops:shop-info' pk=user.id %}"
                   class="account-menu--item {% if request.resolver_match.url_name == 'shop-info' %} account-menu--item--active {% endif %}">

                    <i class="fas fa-store fa-2x pt-1 pb-1 mr-3"></i>
                    {% trans 'Управление магазинами' %}
                </a>
            {% endif %}

            {% if account.courier %}
                <a href="{% url 'delivery:orders' %}"
                   class="account-menu--item {% if request.resolver_match.url_name == 'orders' %} account-menu--item--active {% endif %}">

                    <i class="fas fa-truck fa-2x pt-1 pb-1 mr-3"></i>
                    {% trans 'Панель доставки' %}
                </a>
            {% endif %}

        {% endif %}
    </div>
</div>

modules/users/templates/history-orders.html
{% extends 'layout/basic.html' %}
{% load thumbnail %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Мои заказы' %}{% endblock %}


{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb col-md-12 mt-5 mb-5">
                <li class="breadcrumb-item">
                    <a class="breadcrumb-link" href="/">{% trans 'Главная' %}</a>
                </li>
                <li class="breadcrumb-item">
                    <a class="breadcrumb-link" href="{% url 'users:account-detail' pk=user.id %}">
                        {% trans 'Профиль' %}</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">{% trans 'Order History' %}</li>
            </ol>
        </nav>
        <div class="row pb-5 col-md-12">
            <div class="col-md-3">
                {% include 'account-sidebar-block.html' %}
            </div>
            <div class="col-md-9">
                {{ account.get_product_count_active }}
                <div class="account-products">
                    <h1 class="h1 title">{% trans 'Order History' %}</h1>
                    <table class="table mt-3">
                        <thead>
                        <tr>
                            <th scope="col"># ORDER</th>
                            <th scope="col">DATE</th>
                            <th scope="col">STATUS</th>
                            <th scope="col">TOTAL</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for order in account.order_set.all %}
                            <tr>
                                <th scope="row"><a
                                        href="{% url 'users:history-detail-orders' pk=account.id order_pk=order.id %}">{{ order.id }}</a>
                                </th>
                                <td>{{ order.created_at }}</td>
                                <td>{{ order.status }}</td>
                                <td>{{ order.total_price }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>


            </div>
        </div>
    </div>

{% endblock %}