bboard/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('api/', include('modules.api.urls')),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),

]

urlpatterns += i18n_patterns(
    path('', include('modules.main.urls', namespace='main')),
    path('', include('modules.cms.urls', namespace='cms')),
    path('', include('modules.shops.urls', namespace='shops')),
    path('', include('modules.cart.urls', namespace='cart')),
    path('', include('modules.users.urls', namespace='users')),
    path('', include('modules.orders.urls', namespace='orders')),
    path('', include('modules.delivery.urls', namespace='delivery')),
    path('', include('modules.favorite.urls', namespace='favorite')),
    # path('', include('modules.chat.urls', namespace='chat')),
    path('', include('social_django.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        ] + urlpatterns

modules/delivery/urls.py
from django.urls import path

from modules.delivery.views import (DeliverListView,
                                    OrderDetailView,
                                    OrderListView,
                                    DeliverHistoryListView,
                                    OrderTake,
                                    OrderCancel,
                                    OrderDone
                                    )

app_name = 'delivery'

urlpatterns = [
    path('delivery/', DeliverListView.as_view(), name='index'),
    path('delivery/orders', OrderListView.as_view(), name='orders'),
    path('delivery/order-detail/<int:pk>', OrderDetailView.as_view(), name='order-detail'),
    path('delivery/history', DeliverHistoryListView.as_view(), name='history'),
    path('delivery/ordertake/<int:pk>', OrderTake.as_view(), name='order-take'),
    path('delivery/ordercancel/<int:pk>', OrderCancel.as_view(), name='order-cancel'),
    path('delivery/orderdone/<int:pk>', OrderDone.as_view(), name='order-done'),
]

modules/main/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from modules.main.views import (
    ProductDetail,
    ItemCreateView,
    ItemEditView,
    ItemDeleteView,
    CategoryList,
    SearchResultView,
    IndexView,
    ItemList,

)

app_name = 'main'

urlpatterns = [
    path('advert/', ItemList.as_view(), name='advert-list'),
    path('product/', ItemList.as_view(), name='product-list'),

    path('product/<int:pk>', ProductDetail.as_view(), name='product-detail'),
    path('product/create', ItemCreateView.as_view(), name='product-create'),
    path('product/edit/<int:pk>', never_cache(ItemEditView.as_view()), name='product-edit'),
    path('product/delete/<int:pk>', ItemDeleteView.as_view(), name='product-delete'),

    # Работа с категориями
    path('category/<int:pk>', CategoryList.as_view(), name='category'),

    path('search/', SearchResultView.as_view(), name='search-result'),

    path('city/<int:city_pk>/', IndexView.as_view(), name='index'),

    path('', IndexView.as_view(), name='index'),
]

modules/delivery/models.py
from django.db import models

from modules.orders.models import Order
from modules.users.models import Account


class Deliveryman(models.Model):
    deliverman = models.ForeignKey(
        Account,
        on_delete=models.CASCADE,
        verbose_name='Доставщик'
    )
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        verbose_name="Заказ"
    )
    taken_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Взят в исполнение')
    completed_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Выполнен')

    class Meta:
        verbose_name = 'Доставщик'
        verbose_name_plural = 'Доставщики'
        unique_together = ['deliverman', 'order']

    def __str__(self):
        return f"{self.order} - {self.deliverman.username}"

modules/delivery/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import ListView, DetailView, TemplateView

from modules.delivery.models import Deliveryman
from modules.orders.models import Order, Status


class DeliverListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'delivery.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_orders'] = Deliveryman.objects.filter(deliverman=self.request.user,
                                                              order__status__name='В работе')

        return context


class DeliverHistoryListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'history.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['active_orders'] = Deliveryman.objects.filter(deliverman=self.request.user,
                                                              order__status__name='Выполнен')

        return context


class OrderListView(LoginRequiredMixin, ListView):
    model = Order
    template_name = 'order-list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['open_orders'] = Order.objects.filter(status__name='Новый')

        return context


class OrderDetailView(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'order-detail.html'
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = Order.objects.get(id=self.kwargs.get('pk'))
        # order1 = Order.objects.filter(status__name='В работе')
        if order.status.name != 'Новый':
            context['deliverman'] = Deliveryman.objects.filter(order=order)[0]

        return context


# TODO срок исполения заказ?

class OrderTake(LoginRequiredMixin, TemplateView):

    def post(self, request, pk):

        if request.is_ajax():
            # check deliverman count order
            # добавить проверку, сейчас сохраняются дубликаты... полу пофиксил дисейблом кнопки на жсе
            Deliveryman.objects.create(deliverman=self.request.user, order=Order.objects.get(id=pk))

            order = Order.objects.get(id=pk)
            order.status = Status.objects.filter(name='В работе')[0]
            order.save()

            return JsonResponse({'message': 'success'})
        else:
            return JsonResponse({'message': 'Failed'})


class OrderCancel(LoginRequiredMixin, TemplateView):

    def post(self, request, pk):

        if request.is_ajax():
            order = Order.objects.get(id=pk)
            order.status = Status.objects.filter(name='Новый')[0]
            order.save()
            # TODO нужен ли лог отмен заказов?

            order_deliver = Deliveryman.objects.filter(deliverman=self.request.user, order=order)[0]
            order_deliver.delete()

            return JsonResponse({'message': 'success'})
        else:
            return JsonResponse({'message': 'Failed'})


class OrderDone(LoginRequiredMixin, TemplateView):

    def post(self, request, pk):

        if request.is_ajax():
            # check deliverman count order
            # добавить проверку, сейчас сохраняются дубликаты... полу пофиксил дисейблом кнопки на жсе

            order = Order.objects.get(id=pk)
            if self.request.user == order.deliveryman_set.first().deliverman:
                order.status = Status.objects.filter(name='Выполнен')[0]
                order.save()
                # TODO время выполнения в модель Deliveryman вроде бы проставляется само...
                # order_deliver = Deliveryman.objects.filter(deliverman=self.request.user, order=order)[0]
                # order_deliver.completed_at = datetime.now()
                # order_deliver.save()

            return JsonResponse({'message': 'success'})
        else:
            # TODO: ошибки?
            return JsonResponse({'message': 'Failed'})

modules/delivery/templates/delivery.html
{% extends 'layout/base-delivery.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Admin Dashboard' %}{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/statistic.css' %}">
{% endblock %}

{% block content %}
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        {% include 'header.html' %}

        <div class="app-main">
            {% include 'layout/left-menu.html' %}
            <div class="app-main__outer">
                <div class="app-main__inner">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="main-card mb-3 card">
                                <h2 class="card-header">{% trans 'Список активных заказов' %}</h2>
                                <div class="table-responsive">
                                    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                                        <thead>
                                        <tr>
                                            <th class="text-center">{% trans 'Номер заказа' %}</th>
                                            <th class="text-center">{% trans 'Дата заказа' %}</th>
                                            <th class="text-center">{% trans 'Статус' %}</th>
                                            {#                                            <th>{% trans 'Магазин' %}</th>#}
                                            <th class="text-center">{% trans 'Товар' %}</th>
                                            <th class="text-center">{% trans 'Адрес доставки' %}</th>
                                            <th class="text-center">{% trans 'Детали' %}</th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        {% for item in active_orders %}
                                            <tr>
                                                <td class="text-center text-muted">{{ item.order.id }}</td>
                                                <td class="text-center text-muted">{{ item.order.created_at }}</td>
                                                <td class="text-center text-muted">{{ item.order.status }}</td>
                                                {#                                                <td>#}
                                                {#                                                    <div class="widget-content p-0">#}
                                                {#                                                        <div class="widget-content-wrapper">#}
                                                {#                                                            <div class="widget-content-left flex2">#}
                                                {#                                                                <div class="widget-heading">{{ order.shop }}</div>#}
                                                {#                                                                <div class="widget-subheading opacity-7">{{ order.shop.address }}</div>#}
                                                {#                                                            </div>#}
                                                {#                                                        </div>#}
                                                {#                                                    </div>#}
                                                {#                                                </td>#}
                                                <td class="">
                                                    <ul>
                                                        {% for product in item.order.product_list %}
                                                            <li>
                                                                <a target="_blank"
                                                                   href="{{ product.get_absolute_url }}">{{ product.name }}</a>

                                                                - {{ product.price }} {{ product.currency.name }}</li>
                                                        {% endfor %}

                                                    </ul>
                                                </td>
                                                <td class="text-center">{{ item.order.customer_address }}</td>
                                                <td class="text-center">
                                                    <button type="button" id="PopoverCustomT-1"
                                                            style="border-color: #3ac47d; background-color: #3ac47d"
                                                            class="btn btn-primary btn-sm">
                                                        <a href="{% url 'delivery:order-detail' pk=item.order.pk %}"
                                                           style="text-decoration: none; color: white">{% trans 'Детали' %}</a>
                                                    </button>

                                                </td>
                                            </tr>
                                        {% endfor %}

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

modules/delivery/templates/header.html
<div class="app-header header-shadow bg-primary header-text-light">
    <div class="app-header__logo">
        <h4>
            <a style="color: white" href="{% url 'delivery:index' %}">Senca.Delivery</a>
        </h4>
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic"
                        data-class="closed-sidebar">
                            <span class="hamburger-box">
                                <span class="hamburger-inner"></span>
                            </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                        <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                        </span>
            </button>
        </div>
    </div>
</div>

modules/delivery/templates/order-detail.html
{% extends 'layout/base-delivery.html' %}
{% load static %}
{% load i18n %}

{% block title %}{% trans 'Детальная информация о заказе: ' %} {{ order.id }}{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/statistic.css' %}">
{% endblock %}

{% block content %}
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        {% include 'header.html' %}

        <div class="app-main">
            {% include 'layout/left-menu.html' %}
            <div class="app-main__outer">
                <div class="app-main__inner">
                    <div class="row">
                        <h3 style="color: #f7b924; padding-bottom: 20px">{% trans 'Детальная информация' %}</h3>
                        <div class="col-md-12">
                            {# TODO товары из разных магазинов #}
                            <h4><b>{% trans 'Магазин' %}</b>: {{ order.cart }}</h4>
                            <h4><b>{% trans 'Адрес доставки' %}</b>: {{ order.customer_address }}</h4>
                            <h4><b>{% trans 'Заказчик' %}</b>: {{ order.customer_name }}</h4>
                            <h4><b>{% trans 'Почта' %}</b>: {{ order.customer_email }}</h4>
                            <h4><b>{% trans 'Номер телефона' %}</b>: {{ order.customer_phone }}</h4>
                            <div class="main-card mb-3 card">
                                <div class="card-header">{% trans 'Список товаров' %}</div>
                                <div class="table-responsive">
                                    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                                        <thead>
                                        <tr>
                                            <th class="text-center">#</th>
                                            <th class="text-center">{% trans 'Магазин' %}</th>
                                            <th class="text-center">{% trans 'Товар' %}</th>
                                            <th class="text-center">{% trans 'Количество' %}</th>
                                            <th class="text-center">{% trans 'Цена' %}</th>
                                            <th class="text-center">{% trans 'Валюта' %}</th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        {% for product in order.get_product_in_order %}
                                            <tr>
                                                <td class="text-center text-muted">
                                                    <a href="{% url 'main:product-detail' pk=product.id %}">{{ product.id }}</a>
                                                </td>
                                                <td class="text-center text-muted">{{ product.shop.name }}<br> {{ product.shop.address }}
                                                </td>
                                                <td class="text-center text-muted">{{ product.name }}</td>
                                                <td class="text-center text-muted">{{ product.count }}</td>
                                                <td class="text-center text-muted">{{ product.price }}</td>
                                                <td class="text-center text-muted">{{ product.currency.name }}</td>
                                                {# FIXME Добавить количество товаров #}

                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>

                                </div>

                            </div>
                            <h4 class="h4 lead text-right"> Total sum: {{ order.total_price }}</h4>
                            <hr>
                            <div id="message"></div>
                            {% if user.is_authenticated %}

                                {% if order.status.name == 'Новый' %}
                                    <a class="btn btn-info text-white" type="submit" id="take_order"
                                       data-info="{{ order.id }}" role="button">{% trans "Принять заказ" %}</a>
                                {% endif %}

                                {% if order.status.name == 'В работе' %}
                                    <p id="in_work"> Заказ в работе доставщика: <b>{{ deliverman.deliverman }}</b>
                                        c <i>{{ deliverman.taken_at }}</i></p>

                                    {% if user == deliverman.deliverman %}
                                        <a class="btn btn-danger text-white" type="submit" id="cancel_order"
                                           data-info="{{ order.id }}" role="button">{% trans "Отменить доставку" %}</a>

                                        <a class="btn btn-success text-white" type="submit" id="order_done"
                                           data-info="{{ order.id }}" role="button">{% trans "Заказ выполнен" %}</a>

                                    {% endif %}

                                {% endif %}

                                {% if order.status.name == 'Выполнен' %}
                                    <p> Заказ выполнен доставщиком: <b>{{ deliverman.deliverman }}</b>
                                        c <i>{{ deliverman.completed_at }}</i></p>
                                {% endif %}

                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        {% if order.status.name == 'Новый' %}
            window.addEventListener("load", function (event) {

                document.getElementById("take_order").addEventListener("click", () => take_order());

                function take_order(event) {

                    $.ajax({
                        method: 'POST',
                        url: "{% url "delivery:order-take" order.id %}",
                        data: {
                            'user': {{ user.id }},
                            'order_id': {{ order.id }},
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                        },
                        dataType: 'json',

                    }).done(function (response) {
                        console.log("resp", response.message)

                        if (response.message === "success") {
                            $("#message").html(`<div class="alert alert-primary alert-dismissible fade show" role="alert">
            {% trans 'Заказ принят!' %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>`);
                            const button = document.getElementById("take_order")
                            {#button.removeEventListener()#}
                            button.style.display = 'none'
                            $('.alert').fadeOut(3000, function () {
                                $('#alertFadeOut').text('');
                            });
                        }
                    });
                }
            });
        {% endif %}

        {% if order.status.name == 'В работе' %}
            window.addEventListener("load", function (event) {

                document.getElementById("cancel_order").addEventListener("click", () => cancel_order());

                function cancel_order(event) {

                    $.ajax({
                        method: 'POST',
                        url: "{% url "delivery:order-cancel" order.id %}",
                        data: {
                            'user': {{ user.id }},
                            'order_id': {{ order.id }},
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                        },
                        dataType: 'json',

                    }).done(function (response) {
                        console.log("resp", response.message)

                        if (response.message === "success") {
                            $("#message").html(`<div class="alert alert-primary alert-dismissible fade show" role="alert">
            {% trans 'Доставка отменена!' %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>`);
                            const button = document.getElementById("cancel_order")
                            let text = document.getElementById('in_work')
                            text.style.display = 'none'
                            button.style.display = 'none'
                            $('.alert').fadeOut(3000, function () {
                                $('#alertFadeOut').text('');
                            });
                        }
                    });
                }

                document.getElementById('order_done').addEventListener("click", () => order_done())

                function order_done(event) {

                    $.ajax({
                        method: 'POST',
                        url: "{% url "delivery:order-done" order.id %}",
                        data: {
                            'user': {{ user.id }},
                            'order_id': {{ order.id }},
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                        },
                        dataType: 'json',

                    }).done(function (response) {
                        console.log("resp", response.message)

                        if (response.message === "success") {
                            $("#message").html(`<div class="alert alert-primary alert-dismissible fade show" role="alert">
            {% trans 'Доставка выполнена!' %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>`);
                            const cancel_order = document.getElementById("cancel_order")
                            const order_done = document.getElementById("order_done")

                            cancel_order.style.display = 'none'
                            order_done.style.display = 'none'

                            let text = document.getElementById('in_work')
                            text.style.display = 'none'

                            $('.alert').fadeOut(3000, function () {
                                $('#alertFadeOut').text('');
                            });
                        }
                    });
                }
            });
        {% endif %}
    </script>

{% endblock %}

modules/delivery/templates/order-list.html
{% extends 'layout/base-delivery.html' %}
{% load static %}
{% load i18n %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/list-orders.css' %}">
{% endblock %}

{% block title %}{% trans 'Заказы' %}{% endblock %}

{% block content %}
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        {% include 'header.html' %}

        <div class="app-main">
            {% include 'layout/left-menu.html' %}
            <div class="app-main__outer">
                <div class="app-main__inner">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="main-card mb-3 card">
                                <h3 class="card-header">{% trans 'Список заказов' %}</h3>
                                <div class="table-responsive">
                                    <table class="align-middle mb-0 table table-borderless table-striped table-hover">
                                        <thead>
                                        <tr>
                                            <th class="text-center">#</th>
                                            <th class="text-center">{% trans 'ФИО' %}</th>
                                            <th class="text-center">{% trans 'Адрес доставки' %}</th>
                                            <th class="text-center">{% trans 'Номер телефона' %}</th>
                                            <th class="text-center">{% trans 'Дата заказа' %}</th>
                                            <th class="text-center">{% trans 'Статус' %}</th>
                                            <th class="text-center"></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for order in open_orders %}
                                            <tr>
                                                <td class="text-center text-muted">
                                                    <a type="button" id="PopoverCustomT-1"
                                                       class="btn btn-primary btn-sm"
                                                       href="{% url 'delivery:order-detail' pk=order.pk %}">
                                                        {{ order.id }} </a>

                                                </td>
                                                <td class="text-center text-muted">{{ order.customer_name }}</td>
                                                <td class="text-center">{{ order.customer_address }}</td>
                                                <td class="text-center">{{ order.customer_phone }}</td>
                                                <td class="text-center">{{ order.created_at }}</td>
                                                <td class="text-center">
                                                    <div class="badge {% if order.status == 'Статус Открыт' %}badge-warning
                                                    {% elif order.status == 'Принят' %}badge-info
                                                    {% elif order.status == 'Закрыт' %}badge-success{% endif %}">
                                                        {{ order.status }}</div>
                                                </td>

                                                {% if order.deliveryman == None %}
                                                    <td class="text-center">
                                                        <a type="button" id="PopoverCustomT-1"
                                                           class="btn btn-primary btn-sm"
                                                           href="{% url 'delivery:order-detail' pk=order.pk %}">
                                                            {% trans 'Детали' %} </a>
                                                    </td>
                                                {% else %}
                                                    <td class="text-center">
                                                        <button type="button" id="PopoverCustomT-1"
                                                                style="border-color: #3ac47d; background-color: #3ac47d"
                                                                class="btn btn-primary btn-sm">
                                                            {{ order.deliveryman }}
                                                        </button>
                                                    </td>
                                                {% endif %}

                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}