bboard/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('api/', include('modules.api.urls')),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),

]

urlpatterns += i18n_patterns(
    path('', include('modules.main.urls', namespace='main')),
    path('', include('modules.cms.urls', namespace='cms')),
    path('', include('modules.shops.urls', namespace='shops')),
    path('', include('modules.cart.urls', namespace='cart')),
    path('', include('modules.users.urls', namespace='users')),
    path('', include('modules.orders.urls', namespace='orders')),
    path('', include('modules.delivery.urls', namespace='delivery')),
    path('', include('modules.favorite.urls', namespace='favorite')),
    # path('', include('modules.chat.urls', namespace='chat')),
    path('', include('social_django.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        ] + urlpatterns

modules/cart/urls.py
from django.urls import path

from modules.cart.views import CartDetail, CartAdd, CartRemoveProduct, CartClear

app_name = 'cart'

urlpatterns = [
    path('cart/', CartDetail.as_view(), name='cart-detail'),
    path('cart/add/<int:pk>/', CartAdd.as_view(), name='cart-add'),
    path('cart/remove/<int:product_id>/', CartRemoveProduct.as_view(), name='cart-remove'),
    path('cart/cart-clear', CartClear.as_view(), name='cart-clear'),
]

modules/favorite/urls.py
from django.urls import path

from modules.favorite.views import FavoriteListView, FavoriteLike

app_name = 'favorite'

urlpatterns = [
    path('account/favorite', FavoriteListView.as_view(), name='favorite-list'),
    path('account/favorite-like', FavoriteLike.as_view(), name='favorite-like'),
]

modules/main/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache

from modules.main.views import (
    ProductDetail,
    ItemCreateView,
    ItemEditView,
    ItemDeleteView,
    CategoryList,
    SearchResultView,
    IndexView,
    ItemList,

)

app_name = 'main'

urlpatterns = [
    path('advert/', ItemList.as_view(), name='advert-list'),
    path('product/', ItemList.as_view(), name='product-list'),

    path('product/<int:pk>', ProductDetail.as_view(), name='product-detail'),
    path('product/create', ItemCreateView.as_view(), name='product-create'),
    path('product/edit/<int:pk>', never_cache(ItemEditView.as_view()), name='product-edit'),
    path('product/delete/<int:pk>', ItemDeleteView.as_view(), name='product-delete'),

    # Работа с категориями
    path('category/<int:pk>', CategoryList.as_view(), name='category'),

    path('search/', SearchResultView.as_view(), name='search-result'),

    path('city/<int:city_pk>/', IndexView.as_view(), name='index'),

    path('', IndexView.as_view(), name='index'),
]

modules/shops/urls.py
from django.urls import path

from modules.shops.views import (
    ShopsList,
    ShopPageView,
    ShopCreateView,
    ShopInfoView,
    ShopProductCreate,
    ShopProductEdit,
    ShopProductDeleteView,
    ShopInfoEdit,
    ShopProductList,
    ShopOrdersListView,
    ShopCreateSuccsessView,
)

app_name = 'shops'

urlpatterns = [
    # список всех магазинов
    path('shops/', ShopsList.as_view(), name='shops-list'),

    # заявка на создание магазина
    path('shop/shop-create/', ShopCreateView.as_view(), name='shop-create'),
    path('shop/shop-create/success', ShopCreateSuccsessView.as_view(), name='shop-create-success'),

    # страница магазина
    path('shop/<int:pk>', ShopPageView.as_view(), name='shop-page'),

    # управление магазином
    path('account/<int:pk>/shops/', ShopInfoView.as_view(), name='shop-info'),
    path('shop/info/<int:pk>/edit', ShopInfoEdit.as_view(), name='shop-info-edit'),

    # список товаров магазина
    path('shop/<int:pk>/product-list', ShopProductList.as_view(), name='crud-product'),

    # создание товара в определенном магазине
    path('shop/<int:shop_pk>/create-product', ShopProductCreate.as_view(), name='create-product'),

    # редактирование товара в определенном магазине
    # path('shop/<int:shop_pk>/product/<int:pk>/edit/', ShopProductEdit.as_view(), name='shop-product-edit'),
    path('shop/<int:shop_pk>/product/<int:pk>/edit/', ShopProductEdit.as_view(), name='product-edit'),
    path('shop/product/<int:pk>/delete/', ShopProductDeleteView.as_view(), name='product-delete'),

    # список заказов
    path('shop/<int:shop_pk>/orders', ShopOrdersListView.as_view(), name='order-list'),
]

modules/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordResetCompleteView, PasswordChangeDoneView, \
    PasswordResetConfirmView, PasswordResetView
from django.urls import path, reverse_lazy

from modules.users.views import (
    ValidateView,
    AccountLoginView,
    RegistrationView,
    AccountDetailView,
    AccountSettingsView,
    HistoryOrderView,
    HistoryOrderDetailView
)

app_name = 'users'

urlpatterns = [
    # вход/выход/регистрация
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),

    path('registration', RegistrationView.as_view(), name='registration'),
    path('registration/validate-email/', ValidateView.as_view()),

    path('account/settings/<int:pk>', AccountSettingsView.as_view(), name='settings-profile'),

    # my bb
    path('account/<int:pk>', AccountDetailView.as_view(), name='account-detail'),

    # history orders
    path('account/<int:pk>/orders/', HistoryOrderView.as_view(), name='history-orders'),
    path('account/<int:pk>/orders/<int:order_pk>', HistoryOrderDetailView.as_view(), name='history-detail-orders'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    # reset password
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='registration/password-change-done.html'),
         name='password_change_done'),

    path('password_change/',
         PasswordChangeView.as_view(success_url=reverse_lazy('users:password_change_done'),
                                    template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/',
         PasswordResetView.as_view(success_url=reverse_lazy('users:password_reset_complete')),
         name='password-reset'),

    path('reset/done/',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

modules/main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.detail import SingleObjectMixin

from modules.analytics.decorators import counted
from modules.cart.models import Cart
from modules.catalog.models import Category
from modules.main.forms import AddItemForm, EditItemForm, ItemFilterForm
from modules.main.models import Item, Image
from modules.shops.models import Shop
from modules.users.models import City, Account


class CartItemCountMixin(SingleObjectMixin, View):
    object = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.request.user.is_authenticated:
            user_cart = Cart.objects.filter(user=self.request.user,
                                            is_active=True)
            if user_cart.count() > 0:

                context['cart_items_count'] = user_cart.first().items.count()

            else:
                Cart.objects.create(user=self.request.user)

        return context


class IndexView(ListView, CartItemCountMixin):
    template_name = 'main/index.html'

    def get_queryset(self):
        queryset = []

        if self.kwargs.get("city_pk") is not None:
            queryset = Item.objects.filter(city_bb_id=self.kwargs.get('city_pk')).prefetch_related()

            return queryset

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # TODO: Add pagination
        context["advert_list"] = Item.objects.select_related(
            'category', 'city_bb', 'currency'
        ).prefetch_related(
            'product_image_sets'
        ).filter(
            is_active=True,
            commercial=False).distinct()[:10]

        context["product_list"] = Item.objects.select_related(
            'city_bb', 'currency',
        ).prefetch_related(
            'product_image_sets', 'shop'
        ).filter(is_active=True, commercial=True)[:10]

        context['shops_list_brand'] = Shop.objects.filter(confirmation=True, product_sets__gte=0).order_by(
            'product_sets')[:10].only('id', 'name', 'brand_image')
        # context["food_list"] = Item.objects.filter(
        # category__in=Category.objects.get(name="Фастфуд").get_children().values('id'))[:10]

        context['popular_item'] = Item.objects.all().select_related(
            'shop', 'currency', 'city_bb'
        ).prefetch_related(
            'product_image_sets',
        ).order_by('-pagehit__count')[:10]

        context["q"] = f'q={self.request.GET.get("q")}&'

        if self.kwargs.get('city_pk'):
            # print(self.kwargs.get('city_pk'))
            context["city_name"] = City.objects.get(id=self.kwargs.get('city_pk'))
            context['item_count'] = Item.objects.filter(city_bb_id=self.kwargs.get('city_pk')).count()

        return context


def filter_facets(facets, qs, form, filters):
    for query_param, filter_param in filters:
        value = form.cleaned_data[query_param]

        if value:
            selected_value = value
            facets['selected'][query_param] = selected_value
            filter_args = {filter_param: value}

            # if 'price__gte' in filter_args:
            #     qs = qs.filter(**filter_args).order_by('price')
            #
            # if 'price__lte' in filter_args:
            #     qs = qs.filter(**filter_args).order_by('price')

            # print('filter_args', filter_args)

            qs = qs.filter(**filter_args).distinct()

    return qs


class ItemList(ListView, CartItemCountMixin):
    template_name = 'main/item-list.html'
    context_object_name = 'product_list'
    paginate_by = 12

    def get_queryset(self):
        # order=asc
        # order=desc

        qs = Item.objects.filter(is_active=True).select_related('currency')

        form = ItemFilterForm(data=self.request.GET)

        facets = {
            "selected": {},
            "categories": {
                # "category": form.fields["category"].queryset,
                "price__gte": form.fields["price__gte"],
                "price__lte": form.fields["price__lte"],
                "commercial": form.fields["commercial"],
            }
        }
        if form.is_valid():
            filters = (
                # ("category", "category"),
                ("price__gte", "price__gte"),
                ("price__lte", "price__lte"),
                ("commercial", 'commercial')
            )
            qs = filter_facets(facets, qs, form, filters)

            return qs

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # TODO fix count after filter
        context['item_count'] = self.object_list.count()
        context['filter_form'] = ItemFilterForm(self.request.GET)

        return context


class CategoryList(ListView, CartItemCountMixin):
    model = Category
    template_name = 'main/category-list.html'
    context_object_name = 'product_list'
    paginate_by = 12

    def get_queryset(self):

        form = ItemFilterForm(data=self.request.GET)

        facets = {
            "selected": {},
            "categories": {
                # "category": form.fields["category"].queryset,
                "price__gte": form.fields["price__gte"],
                "price__lte": form.fields["price__lte"],
                "commercial": form.fields["commercial"],
            }
        }

        qs = Item.objects.filter(is_active=True).select_related('currency')

        if self.kwargs.get("pk") is not None:

            # проверяем суперкатегория это или нет
            main_category = Category.objects.get(id=self.kwargs.get("pk"))

            # если, суперкатегория
            if main_category.is_root_node():

                # получаем все подкатегории
                sub_category_list = main_category.get_children().only('id')

                # получаем список всех продуктов в категориях
                item_list = Item.objects.filter(category_id__in=sub_category_list, is_active=True).select_related(
                    'city_bb')
            else:
                # для обычной категории возвращаем её товары
                item_list = Item.objects.filter(category__id=self.kwargs.get('pk'), is_active=True)

            if form.is_valid():
                filters = (
                    # ("category", "category"),
                    ("price__gte", "price__gte"),
                    ("price__lte", "price__lte"),
                    ("commercial", 'commercial')
                )
                qs = filter_facets(facets, item_list, form, filters)

                return qs

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['filter_form'] = ItemFilterForm(self.request.GET)

        return context


@method_decorator(counted, name='dispatch')
class ProductDetail(DetailView, CartItemCountMixin):
    model = Item
    template_name = 'main/item-detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['account'] = Account.objects.get(id=self.request.user.id)
        # print(Item.objects.get(id=self.kwargs['pk']).shop.product_sets.all().count())
        # Item.objects.filter(commercial=True)[0].shop.product_sets.only('id').count()

        if self.object.commercial:
            item_id = self.object.id
            context['shop'] = Shop.objects.get(id=Item.objects.get(id=item_id).shop_id)

        return context


class FormMixin(object):
    object = None

    def get(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)

        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def get_formset_class(self):
        return self.formset_class

    def get_formset(self, formset_class):
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'instance': self.object
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form, formset):
        form.instance.author = self.request.user
        self.object = form.save()
        formset.instance = self.object
        formset.save()

        if hasattr(self, 'get_success_message'):
            self.get_success_message(form)

        return HttpResponseRedirect(self.object.get_absolute_url())

    def form_invalid(self, form, formset):
        print(form, formset)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


class ItemCreateView(LoginRequiredMixin, FormMixin, CreateView, CartItemCountMixin):

modules/main/templates/main/index.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load i18n %}
{% load counter %}
{% load thumbnail %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/owl-item.css' %}">
{% endblock %}

{% block title %}{% trans 'Главная' %}{% endblock %}


{% block content %}
    <div class="container pb-5">
        <section>
            <h2 class="h2 title pt-5 pb-5">
                {% trans 'Товары в магазинах' %}
                {% if city_name %}
                    {% trans 'в городе' %} {{ city_name }}
                {% endif %}
            </h2>
            <div class="pb-3">
                <div class="d-flex flex-row flex-wrap">
                    {% for product in product_list %}
                        {% include 'main/product-card.html' %}
                    {% endfor %}
                    <span id="message"></span>
                </div>
                <div class="pt-3">
                    <div class="col-md-12 offset-md-10">
                        <a href="{% url 'shops:shops-list' %}"
                           class="btn btn-info">{% trans 'Все товары магазинов' %}</a>
                    </div>
                </div>
            </div>
        </section>
        <section>
            <h2 class="h2 title pt-5 pb-5">{% trans 'Частные объявления' %}
            </h2>
            <div class="pb-3">
                <div class="d-flex flex-row flex-wrap">
                    {% for product in advert_list %}
                        {% include 'main/product-card.html' %}
                    {% endfor %}
                </div>
                <div class="pt-3 row">
                    <div class="col-md-12 offset-md-10">
                        <a href="{% url 'main:advert-list' %}"
                           class="btn btn-info">{% trans 'Смотреть все объявления' %}</a>
                    </div>
                </div>
            </div>
        </section>
        <section>
            <h2 class="h2 title pt-5 pb-5">{% trans 'Популярные товары' %}
            </h2>
            <div class="pb-3">
                <div class="d-flex flex-row flex-wrap">
                    {% for product in popular_item %}
                        {% include 'main/product-card.html' %}
                    {% endfor %}
                </div>
            </div>
        </section>
        <section>
            <h2 class="h2 title pt-5 pb-5">{% trans 'С нами сотрудничают' %}
            </h2>
            <div class="pb-3">
                <div class="d-flex flex-row flex-wrap">
                    {% for shop in shops_list_brand %}
                        {% include 'main/index-shop-brand-card.html' %}
                    {% endfor %}
                </div>
            </div>
        </section>
    </div>
{% endblock %}
{% block script %}
    <script>
        window.addEventListener("load", function (event) {

            {% if user.is_authenticated %}

                $(".js-btn-add-cart").click(function () {

                    {#$(this).addClass('disabled')#}

                    let product_id = $(this).data("product_id");
                    let product_url = $(this).data("product_url");

                    $.ajax({
                        method: 'post',
                        url: product_url,
                        data: {
                            'user': {{ user.id }},
                            'product_id': product_id,
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                        },
                        dataType: 'json',

                    }).done(function (response) {


                        console.log("resp", response.message)

                        if (response.message === "success") {
                            $("#message").html(`<div class="alert alert-primary alert-dismissible fade show" role="alert">
            {% trans 'Товар успешно добавлен в корзину!' %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>`);
                            $('.alert').fadeOut(3000, function () {
                                $('#alertFadeOut').text('');
                            });
                        }
                    })
                })

                $(".product-card-like").click(function () {
                    $(this).addClass('like--active');
                    product_card = $(this);
                    {# TODO возможны баги #}

                    $.ajax({
                        method: 'post',
                        url: '{% url 'favorite:favorite-like' %}',
                        data: {
                            'user_id': {{ user.id }},
                            'product_id': $(this).data("id"),
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                        },
                        dataType: 'json',

                    }).done(function (response) {
                        console.log("resp", response.success)

                        if (response.success) {
                            console.log('success')
                        }
                    })
                })

            {#TODO add click info for anonimus user #}

            {% endif %}
        })

    </script>

{% endblock %}

modules/main/templates/main/item-create.html
{% extends 'layout/basic.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load i18n %}
{% load thumbnail %}
{% load crispy_forms_tags %}

{% block title %}{% trans 'Создание объявления' %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb col-md-12 mt-5 mb-5">
                <li class="breadcrumb-item">
                    <a class="breadcrumb-link" href="/">{% trans 'Главная' %}</a>
                </li>
                <li class="breadcrumb-item">
                    <a class="breadcrumb-link" href="{% url 'users:account-detail' pk=user.id %}">
                        {% trans 'Профиль' %}</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">{% trans 'Создание объявления' %}</li>
            </ol>
        </nav>
            <div class="row pb-5">
                <div class="sidebar col-md-3">
                    {% include 'account-sidebar-block.html' %}
                </div>
                <div class="content col-md-6">
                    <h4 class="title">{% trans 'Создание объявления' %}</h4>
                    <div class="row">
                        <div class="mt-5">
                            <form enctype="multipart/form-data" method='post' role="form">
                                {% csrf_token %}
                                {{ formset.management_form }}

                                {{ form|crispy }}

                                {% for form in formset %}
                                    {{ form|crispy }}
                                {% endfor %}

                                <input type='submit' class="btn btn-success" value="{% trans 'Сохранить' %}">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

modules/main/templates/main/owl-item.html
{% load static %}
{% load thumbnail %}
{% load i18n %}

<div class="owl-item"
     href="{{ product.get_absolute_url }}">
    <a class="item-link"
       href="{{ product.get_absolute_url }}">
        <div class="owl-item__favorite">
            <i class="far fa-heart"></i>
        </div>
    </a>
    {% if product.get_main_image %}
        <img class="shop-image"
             height="131" width="131"
             src="{% thumbnail product.get_main_image.images 131x131 crop=scale %}"
             alt="{{ product.name }}">
    {% else %}
        <img class="shop-image"
             height="131" width="131" src="{% static 'img/slider/no-image.png' %}"
             alt="{{ product.name }}">
    {% endif %}
    <figcaption class="info-wrap p-2">
        <a href="{{ product.get_absolute_url }}"
           class="product-name px-2 py-2">{{ product.name }}</a>
        {% if product.city_bb %}
            <span class="city-name">
                {{ product.city_bb }}
            </span>
        {% endif %}
        <hr class="mt-1 mb-1">
        <div class="price__block text-center">
            <div class="product-price mt-2 mb-2">{{ product.price }} {{ product.currency }}</div>
            {% if user.is_authenticated %}
                {% if product.commercial %}
                    <button id="add_cart" class="btn btn-info mt-1 pb-1 js-btn-add-cart mt-auto"
                            data-product_id="{{ product.id }} " style="border-color: #5d719a;"
                            data-product_url="{% url "cart:cart-add" pk=product.id %}">{% trans 'В корзину' %}
                    </button>
                {% endif %}
            {% endif %}

        </div>
    </figcaption>
</div>

modules/main/templates/main/product-card.html
{% load static %}
{% load thumbnail %}
{% load i18n %}

<div class="card card-product-grid">
    {% if product.get_main_image %}
        <a class="img-responsive" href="{{ product.get_absolute_url }}">
            <img class="card-img-top" width="216" height="140"
                 src="{% thumbnail product.get_main_image.images 216x140 crop=scale %}"
                 alt="{{ product.name }}">
        </a>
    {% else %}
        <a class="rounded mx-auto d-block" href="{{ product.get_absolute_url }}">
            {% if product.get_main_image %}
                <img height="131" width="131" src="{% thumbnail product.get_main_image.image 131x131 crop=scale %}"
                     alt="{{ product.name }}">
            {% else %}
                <img class="mx-auto rounded" height="131" width="131" src="{% static 'img/slider/no-image.png' %}"
                     alt="{{ product.name }}">
            {% endif %}
        </a>
    {% endif %}

    <div class="product-card-like" data-id="{{ product.id }}">
        <i class="far fa-heart"></i>
    </div>

    <div class="card-body">
        <h5 class="product-card-title" data-placement="right" title="{{ product.name }}">
            <a class="product-link" href="{{ product.get_absolute_url }}">{{ product.name|truncatechars:19 }}</a>
        </h5>
        <div class="product-card-price">{{ product.price| floatformat }}{{ product.currency }}</div>
        {% if product.city_bb %}
            {{ product.city_bb }}
        {% endif %}

        {% if product.commercial %}
            <button id="add_cart" class="btn btn-info mt-1 pb-1 js-btn-add-cart pull-right"
                    data-product_id="{{ product.id }}"
                    data-product_url="{% url "cart:cart-add" pk=product.id %}">
                {% trans 'В корзину' %}
            </button>
        {% endif %}
    </div>

</div>

modules/main/templates/main/product-confirm-delete.html
{% extends 'layout/basic.html' %}
{% load static %}
{% load i18n %}

{% block title %}
    {% trans 'удалить обьявление' %} {{ product.name }}
{% endblock title %}

{% block script %}
    <script>
        $('#confirm-delete').on('show.bs.modal', function (e) {
            $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
        });
        {# TODO: move this #}
    </script>

{% endblock %}

{% block content %}
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb col-md-12 mt-5 mb-5">
                <li class="breadcrumb-item">
                    <a class="breadcrumb-link" href="/">{% trans 'Главная' %}</a>
                </li>
                <li class="breadcrumb-item">
                    <a class="breadcrumb-link"
                       href="{% url 'users:account-detail' pk=user.id %}">{% trans 'Профиль' %}</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                    {% trans 'Удалить объявление' %} "{{ product.name }}"
                </li>
            </ol>
        </nav>
        <div class="col-sm-6 col-sm-offset-3">

            {% include 'main/product-card.html' %}

            <div class="col-5">
                {% trans 'Вы уверены что хотите удалить?' %}

                <div class="row">
                    <button class="btn btn-danger pull-right mt-3" data-href="/" data-toggle="modal"
                            data-target="#confirm-delete">{% trans 'Удаление объявления' %}
                    </button>
                    <a class="mt-3" href="{% url 'users:account-detail' pk=product.author.id %}">
                        <button type="button" class="btn btn-info">{% trans 'Отмена' %}</button>
                    </a>
                </div>
            </div>


        </div>
        <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true"><!--modal-->
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title">{% trans 'Внимание!' %}</h4>
                    </div>
                    <div class="modal-body">
                        {% trans 'Объявление будет удалено, восстановить не возможно!' %}
                    </div>
                    <div class="modal-footer">
                        <form action="" method="post">
                            {% csrf_token %}
                            <button type="button" class="btn btn-default"
                                    data-dismiss="modal">{% trans 'Отмена' %}</button>
                            <input type="submit" class="btn btn-danger" value="{% trans 'Удалить' %}"/>
                        </form>
                    </div>
                </div>
                <!--/modal-->
            </div>
        </div>

    </div>
{% endblock %}