bboard/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.authtoken')),
    path('api/', include('modules.api.urls')),
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),

]

urlpatterns += i18n_patterns(
    path('', include('modules.main.urls', namespace='main')),
    path('', include('modules.cms.urls', namespace='cms')),
    path('', include('modules.shops.urls', namespace='shops')),
    path('', include('modules.cart.urls', namespace='cart')),
    path('', include('modules.users.urls', namespace='users')),
    path('', include('modules.orders.urls', namespace='orders')),
    path('', include('modules.delivery.urls', namespace='delivery')),
    path('', include('modules.favorite.urls', namespace='favorite')),
    # path('', include('modules.chat.urls', namespace='chat')),
    path('', include('social_django.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        ] + urlpatterns

modules/cart/urls.py
from django.urls import path

from modules.cart.views import CartDetail, CartAdd, CartRemoveProduct, CartClear

app_name = 'cart'

urlpatterns = [
    path('cart/', CartDetail.as_view(), name='cart-detail'),
    path('cart/add/<int:pk>/', CartAdd.as_view(), name='cart-add'),
    path('cart/remove/<int:product_id>/', CartRemoveProduct.as_view(), name='cart-remove'),
    path('cart/cart-clear', CartClear.as_view(), name='cart-clear'),
]

modules/orders/urls.py
from django.urls import path

from modules.orders.views import OrderCreateView

app_name = 'orders'

urlpatterns = [
    path('order/create/', OrderCreateView.as_view(), name='order-create'),
]

modules/shops/urls.py
from django.urls import path

from modules.shops.views import (
    ShopsList,
    ShopPageView,
    ShopCreateView,
    ShopInfoView,
    ShopProductCreate,
    ShopProductEdit,
    ShopProductDeleteView,
    ShopInfoEdit,
    ShopProductList,
    ShopOrdersListView,
    ShopCreateSuccsessView,
)

app_name = 'shops'

urlpatterns = [
    # список всех магазинов
    path('shops/', ShopsList.as_view(), name='shops-list'),

    # заявка на создание магазина
    path('shop/shop-create/', ShopCreateView.as_view(), name='shop-create'),
    path('shop/shop-create/success', ShopCreateSuccsessView.as_view(), name='shop-create-success'),

    # страница магазина
    path('shop/<int:pk>', ShopPageView.as_view(), name='shop-page'),

    # управление магазином
    path('account/<int:pk>/shops/', ShopInfoView.as_view(), name='shop-info'),
    path('shop/info/<int:pk>/edit', ShopInfoEdit.as_view(), name='shop-info-edit'),

    # список товаров магазина
    path('shop/<int:pk>/product-list', ShopProductList.as_view(), name='crud-product'),

    # создание товара в определенном магазине
    path('shop/<int:shop_pk>/create-product', ShopProductCreate.as_view(), name='create-product'),

    # редактирование товара в определенном магазине
    # path('shop/<int:shop_pk>/product/<int:pk>/edit/', ShopProductEdit.as_view(), name='shop-product-edit'),
    path('shop/<int:shop_pk>/product/<int:pk>/edit/', ShopProductEdit.as_view(), name='product-edit'),
    path('shop/product/<int:pk>/delete/', ShopProductDeleteView.as_view(), name='product-delete'),

    # список заказов
    path('shop/<int:shop_pk>/orders', ShopOrdersListView.as_view(), name='order-list'),
]

modules/cart/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

from modules.main.models import Item
from modules.users.models import Account


class Cart(models.Model):
    created_at = models.DateTimeField(default=datetime.now)
    user = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="carts")
    items = models.ManyToManyField(Item)
    is_active = models.BooleanField(default=True, db_index=True, verbose_name='cart active')

    TAX_DELIVERY = 2

    def cart_items(self):
        return self.items.all()

    def summ_items_price(self):
        return sum(item.price for item in self.items.all())

    # price cart with tax
    def get_total_sum(self):

        total_sum = 0

        if self.items.all().count() > 0:
            for item in self.items.all():
                total_sum += item.price

        total_sum += self.TAX_DELIVERY

        return total_sum

    class Meta:
        ordering = ['created_at']
        verbose_name = "Корзина"
        verbose_name_plural = "Корзины"

    def __str__(self):
        return f"{self.user.username}"

modules/cart/forms.py
from django import forms

from modules.cart.models import Cart


class CartForm(forms.ModelForm):

    class Meta:
        model = Cart
        fields = ("user",)

modules/cart/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic import ListView
from django.views.generic.detail import BaseDetailView

from modules.cart.forms import CartForm
from modules.cart.models import Cart
from modules.main.views import CartItemCountMixin


class CartAdd(LoginRequiredMixin, BaseDetailView):
    model = Cart
    form_class = CartForm

    def get_success_url(self):
        return reverse('main:product-detail', args=[self.kwargs.get("pk")])

    def post(self, request, pk):

        add_cart = CartForm(request.POST)

        if request.is_ajax():
            add_cart.save(commit=False)
            add_cart.user = self.request.user.id
            if add_cart.is_valid():
                # Выбираем корзину юзера
                cart_user = Cart.objects.filter(user=self.request.user, is_active=True)

                # если корзина есть, то добавляем товар в корзину
                if cart_user.count() != 0:

                    cart_user[0].items.add(pk)
                    cart_user[0].save()
                # если нету корзины, создаем и добавляем товар
                else:
                    Cart.objects.create(user=self.request.user)
                    cart_user = Cart.objects.filter(user=self.request.user, is_active=True)

                    cart_user[0].items.add(pk)
                    cart_user[0].save()

            else:
                return JsonResponse({'message': 'form Failed'})
            return JsonResponse({'message': 'success'})
        else:
            return JsonResponse({'message': 'failed'})


class CartDetail(LoginRequiredMixin, ListView, CartItemCountMixin):
    template_name = 'cart-detail.html'
    model = Cart

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_cart = Cart.objects.filter(user=self.request.user, is_active=True)

        if user_cart:
            context['cart'] = user_cart[0]

        else:
            Cart.objects.create(user=self.request.user)

        return context


class CartRemoveProduct(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user_cart = Cart.objects.filter(user=self.request.user, is_active=True)

        if user_cart:
            user_cart[0].items.remove(self.kwargs.get('product_id'))

        return HttpResponseRedirect(reverse('cart:cart-detail'))


class CartClear(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user_cart = Cart.objects.filter(user=self.request.user, is_active=True)

        if user_cart:
            user_cart[0].items.clear()

        return HttpResponseRedirect(reverse('cart:cart-detail'))

modules/cart/templates/cart-detail.html
{% extends 'layout/basic.html' %}

{% load static %}
{% load i18n %}
{% load thumbnail %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/cart.css' %}">
{% endblock %}

{% block title %}
    {% trans 'Корзина' %}
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="h1">{% trans 'Корзина' %}</h1>

        <div class="container padding-bottom-3x mb-1 mt-4">
            <!-- Shopping Cart-->
            <div class="table-responsive shopping-cart">
                <table class="table">
                    <thead>
                    <tr>
                        <th>{% trans 'Фото' %}</th>
                        <th>{% trans 'Название' %}</th>
                        <th class="text-center">{% trans 'Количество' %}</th>
                        <th class="text-center">{% trans 'Цена' %}</th>
                        <th class="text-center">
                            <a class="btn btn-sm btn-outline-danger"
                               href="{% url 'cart:cart-clear' %}">{% trans 'Очистить корзину' %}</a>
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for product in cart.items.all %}

                        <tr>
                            <td>
                                <a class="product-thumb" href="{{ product.get_absolute_url }}">
                                    <div class="product-image">
                                        {% if product.get_main_image %}
                                            <img height="131" width="131"
                                                 src="{% thumbnail product.get_main_image.images 131x131 crop=scale %}"
                                                 alt="{{ product.name }}">
                                        {% else %}
                                            <img height="131" width="131" src="{% static 'img/slider/no-image.png' %}"
                                                 alt="{{ product.name }}">
                                        {% endif %}
                                    </div>
                                </a>
                            </td>
                            <td>
                                <div class="product-info">
                                    <h4 class="product-title">
                                        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                    </h4>
                                </div>
                            </td>
                            <td class="text-center align-middle">
                                <div class="count-input">
                                    <input class="form-control" type="number" value="1" id="example-number-input">
                                </div>
                            </td>

                            <td class="text-center text-lg text-medium align-middle">
                                {{ product.price }}{{ product.currency }}</td>

                            <td class="text-center align-middle ">
                                <a class="remove-from-cart" href="{% url 'cart:cart-remove' product_id=product.id %}"
                                   data-toggle="tooltip"
                                   title=""
                                   data-original-title="Remove item"><i
                                        class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    {% endfor %}

                    {% if cart.items.count > 0 %}
                        <tr>
                            <td></td>
                            <td class="font-weight-bolder align-middle">
                                {% trans "Доставка" %}
                            </td>
                            <td class="text-center align-middle"></td>
                            <td class="text-center text-lg text-medium align-middle">2 ლ</td>
                            <td class="text-center align-middle "></td>
                        </tr>
                    {% endif %}

                    </tbody>
                </table>
            </div>
            <div class="shopping-cart-footer">
                <div class="column text-lg">{% trans 'Итог: ' %}<span id="total_sum"
                                                                      class="text-medium">
                    {% if cart.items.count > 0 %}
                        {{ cart.get_total_sum|floatformat }}
                    {% else %}
                        0
                    {% endif %}
                    </span>
                </div>
            </div>
            <div class="shopping-cart-footer">
                <div class="column">
                    <a class="btn btn-outline-secondary" href="{% url "shops:shops-list" %}">
                        <i class="icon-arrow-left"></i>{% trans 'Назад к покупкам' %}</a></div>
                <div class="column">
                    <a id="checkout" class="btn btn-success disabled"
                       href="{% url 'orders:order-create' %}">{% trans 'Оформить' %}</a></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        let total_sum = "{{ cart.get_total_sum|floatformat }}"
        {# Проверяем есть ли в корзине товары - вычитая цену доставки #}
        if (parseInt(total_sum.replace(/\s+/g, '')) - {{ cart.TAX_DELIVERY }} !== 0) {
            document.getElementById("checkout").classList.remove('disabled')
        }

    </script>
{% endblock %}